--- Tests for PopupBuilder fluent API.
--- @module tests.specs.popups.builder_spec

describe("neosapling.popups.builder", function()
  local builder

  before_each(function()
    package.loaded["neosapling.popups.builder"] = nil
    builder = require("neosapling.popups.builder")
  end)

  describe("builder()", function()
    it("returns a builder instance", function()
      local b = builder.builder()
      assert.is_not_nil(b)
    end)

    it("has state table", function()
      local b = builder.builder()
      assert.is_table(b.state)
    end)

    it("state has nil name initially", function()
      local b = builder.builder()
      assert.is_nil(b.state.name)
    end)

    it("state has empty groups initially", function()
      local b = builder.builder()
      assert.is_table(b.state.groups)
      assert.equal(0, #b.state.groups)
    end)

    it("state has nil current_group initially", function()
      local b = builder.builder()
      assert.is_nil(b.state.current_group)
    end)
  end)

  describe(":name()", function()
    it("sets popup name", function()
      local b = builder.builder():name("TestPopup")
      assert.equal("TestPopup", b.state.name)
    end)

    it("returns self for chaining", function()
      local b = builder.builder()
      local result = b:name("Test")
      assert.equal(b, result)
    end)

    it("overwrites previous name", function()
      local b = builder.builder():name("First"):name("Second")
      assert.equal("Second", b.state.name)
    end)
  end)

  describe(":group()", function()
    it("starts new group", function()
      local b = builder.builder():group()
      assert.is_not_nil(b.state.current_group)
    end)

    it("sets heading when provided", function()
      local b = builder.builder():group("Actions")
      assert.equal("Actions", b.state.current_group.heading)
    end)

    it("sets nil heading when not provided", function()
      local b = builder.builder():group()
      assert.is_nil(b.state.current_group.heading)
    end)

    it("returns self for chaining", function()
      local b = builder.builder()
      local result = b:group("Test")
      assert.equal(b, result)
    end)

    it("finalizes previous group when starting new one", function()
      local b = builder.builder()
        :group("First")
        :action("a", "Action A", function() end)
        :group("Second")
      assert.equal(1, #b.state.groups)
      assert.equal("First", b.state.groups[1].heading)
      assert.equal("Second", b.state.current_group.heading)
    end)

    it("accumulates multiple groups", function()
      local b = builder.builder()
        :group("One")
        :group("Two")
        :group("Three")
      -- First two are finalized, third is current
      assert.equal(2, #b.state.groups)
      assert.equal("Three", b.state.current_group.heading)
    end)

    it("group has empty actions array", function()
      local b = builder.builder():group("Test")
      assert.is_table(b.state.current_group.actions)
      assert.equal(0, #b.state.current_group.actions)
    end)
  end)

  describe(":action()", function()
    it("adds action to current group", function()
      local cb = function() end
      local b = builder.builder():group():action("a", "Action A", cb)
      assert.equal(1, #b.state.current_group.actions)
    end)

    it("converts string key to array", function()
      local b = builder.builder():group():action("k", "Key", function() end)
      local action = b.state.current_group.actions[1]
      assert.is_table(action.keys)
      assert.equal(1, #action.keys)
      assert.equal("k", action.keys[1])
    end)

    it("preserves array keys", function()
      local b = builder.builder():group():action({ "a", "b" }, "Multi", function() end)
      local action = b.state.current_group.actions[1]
      assert.is_table(action.keys)
      assert.equal(2, #action.keys)
      assert.equal("a", action.keys[1])
      assert.equal("b", action.keys[2])
    end)

    it("stores description", function()
      local b = builder.builder():group():action("x", "My Description", function() end)
      local action = b.state.current_group.actions[1]
      assert.equal("My Description", action.description)
    end)

    it("stores callback", function()
      local cb = function() return "test" end
      local b = builder.builder():group():action("x", "Test", cb)
      local action = b.state.current_group.actions[1]
      assert.equal(cb, action.callback)
    end)

    it("auto-creates group if none exists", function()
      local b = builder.builder():action("a", "Action", function() end)
      assert.is_not_nil(b.state.current_group)
      assert.is_nil(b.state.current_group.heading)
      assert.equal(1, #b.state.current_group.actions)
    end)

    it("returns self for chaining", function()
      local b = builder.builder():group()
      local result = b:action("a", "A", function() end)
      assert.equal(b, result)
    end)

    it("multiple actions accumulate in same group", function()
      local b = builder.builder()
        :group()
        :action("a", "A", function() end)
        :action("b", "B", function() end)
        :action("c", "C", function() end)
      assert.equal(3, #b.state.current_group.actions)
    end)
  end)

  describe(":build()", function()
    it("returns popup definition", function()
      local def = builder.builder()
        :name("Test")
        :group("Actions")
        :action("a", "Action A", function() end)
        :build()
      assert.is_table(def)
    end)

    it("definition has name", function()
      local def = builder.builder()
        :name("MyPopup")
        :group()
        :action("x", "X", function() end)
        :build()
      assert.equal("MyPopup", def.name)
    end)

    it("definition has groups array", function()
      local def = builder.builder()
        :name("Test")
        :group("G1")
        :action("a", "A", function() end)
        :build()
      assert.is_table(def.groups)
      assert.equal(1, #def.groups)
    end)

    it("groups contain heading and actions", function()
      local def = builder.builder()
        :name("Test")
        :group("MyHeading")
        :action("k", "Key", function() end)
        :build()
      local group = def.groups[1]
      assert.equal("MyHeading", group.heading)
      assert.is_table(group.actions)
    end)

    it("actions contain keys, description, callback", function()
      local cb = function() end
      local def = builder.builder()
        :name("Test")
        :group()
        :action("t", "Test Action", cb)
        :build()
      local action = def.groups[1].actions[1]
      assert.same({ "t" }, action.keys)
      assert.equal("Test Action", action.description)
      assert.equal(cb, action.callback)
    end)

    it("asserts if name not set", function()
      local b = builder.builder():group():action("a", "A", function() end)
      assert.has_error(function()
        b:build()
      end, "Popup must have a name")
    end)

    it("finalizes current group on build", function()
      local def = builder.builder()
        :name("Test")
        :group("Final")
        :action("f", "F", function() end)
        :build()
      assert.equal(1, #def.groups)
      assert.equal("Final", def.groups[1].heading)
    end)

    it("handles multiple groups", function()
      local def = builder.builder()
        :name("Multi")
        :group("Group1")
        :action("a", "A", function() end)
        :group("Group2")
        :action("b", "B", function() end)
        :action("c", "C", function() end)
        :build()
      assert.equal(2, #def.groups)
      assert.equal("Group1", def.groups[1].heading)
      assert.equal(1, #def.groups[1].actions)
      assert.equal("Group2", def.groups[2].heading)
      assert.equal(2, #def.groups[2].actions)
    end)

    it("handles empty groups", function()
      local def = builder.builder()
        :name("Empty")
        :group("EmptyGroup")
        :build()
      assert.equal(1, #def.groups)
      assert.equal(0, #def.groups[1].actions)
    end)
  end)

  describe("fluent API chaining", function()
    it("full chain works correctly", function()
      local called = false
      local def = builder.builder()
        :name("Commit")
        :group("Create")
        :action("c", "Commit", function() called = true end)
        :action({ "a", "A" }, "Amend", function() end)
        :group("Arguments")
        :action("-e", "Edit message", function() end)
        :build()

      assert.equal("Commit", def.name)
      assert.equal(2, #def.groups)
      assert.equal("Create", def.groups[1].heading)
      assert.equal("Arguments", def.groups[2].heading)

      -- Test callback is preserved
      def.groups[1].actions[1].callback()
      assert.is_true(called)
    end)
  end)
end)
